#!/system/bin/sh
if [ "$1" = "" ] || [ "$1" = "status" ] || [ "$1" = "-s" ]; then
    /data/adb/modules/nfqttl/nfqttl status
elif [ "$1" = "log" ] || [ "$1" = "-l" ]; then
    cat /data/local/tmp/ttlfixer_stats.json
elif [ "$1" = "restart" ] || [ "$1" = "-r" ]; then
    killall -9 nfqttl ttlfixer 2>/dev/null
    nohup /data/adb/modules/nfqttl/nfqttl </dev/null >/dev/null 2>&1 &
    echo "GKI Hotspot Shield restarted."
else
    /data/adb/modules/nfqttl/nfqttl "$@"
fi
